### ISSUE TITLE
Test links at the bottom of the chart

### ISSUE THREAD

**Issue by bgrgicak** [kdevnel/ynab-absa-csv-convert-js#44]
Each time I click submit, I get two links with the word _test_ at the bottom of the table. 

Ideally, there should be only one link, and it should have a descriptive name. 

![Screenshot 2021-06-21 at 10 08 57](https://user-images.githubusercontent.com/1199991/122728893-dcf6c380-d278-11eb-8ee8-79092ae38bfc.png)

**Comment by kdevnel** [comment]
@bgrgicak Interesting, I can't seem to replicate this on the latest main branch or on the Github Pages version of the site. 🤔
